#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : gnome-menus
Version  : 3.32.0
Release  : 13
URL      : https://download.gnome.org/sources/gnome-menus/3.32/gnome-menus-3.32.0.tar.xz
Source0  : https://download.gnome.org/sources/gnome-menus/3.32/gnome-menus-3.32.0.tar.xz
Summary  : GNOME menu specifications
Group    : Development/Tools
License  : GPL-2.0 LGPL-2.0
Requires: gnome-menus-data = %{version}-%{release}
Requires: gnome-menus-lib = %{version}-%{release}
Requires: gnome-menus-license = %{version}-%{release}
Requires: gnome-menus-locales = %{version}-%{release}
BuildRequires : buildreq-gnome
BuildRequires : gettext
BuildRequires : perl(XML::Parser)
BuildRequires : pkgconfig(gio-unix-2.0)

%description
gnome-menus
===========
gnome-menus contains the libgnome-menu library, the layout configuration
files for the GNOME menu, as well as a simple menu editor.

%package data
Summary: data components for the gnome-menus package.
Group: Data

%description data
data components for the gnome-menus package.


%package dev
Summary: dev components for the gnome-menus package.
Group: Development
Requires: gnome-menus-lib = %{version}-%{release}
Requires: gnome-menus-data = %{version}-%{release}
Provides: gnome-menus-devel = %{version}-%{release}
Requires: gnome-menus = %{version}-%{release}

%description dev
dev components for the gnome-menus package.


%package lib
Summary: lib components for the gnome-menus package.
Group: Libraries
Requires: gnome-menus-data = %{version}-%{release}
Requires: gnome-menus-license = %{version}-%{release}

%description lib
lib components for the gnome-menus package.


%package license
Summary: license components for the gnome-menus package.
Group: Default

%description license
license components for the gnome-menus package.


%package locales
Summary: locales components for the gnome-menus package.
Group: Default

%description locales
locales components for the gnome-menus package.


%prep
%setup -q -n gnome-menus-3.32.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1557004203
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1557004203
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/gnome-menus
cp COPYING %{buildroot}/usr/share/package-licenses/gnome-menus/COPYING
cp COPYING.LIB %{buildroot}/usr/share/package-licenses/gnome-menus/COPYING.LIB
%make_install
%find_lang gnome-menus
## install_append content
mv %{buildroot}/etc/xdg %{buildroot}/usr/share/. && rmdir %{buildroot}/etc
## install_append end

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/lib64/girepository-1.0/GMenu-3.0.typelib
/usr/share/desktop-directories/AudioVideo.directory
/usr/share/desktop-directories/Development.directory
/usr/share/desktop-directories/Education.directory
/usr/share/desktop-directories/Game.directory
/usr/share/desktop-directories/Graphics.directory
/usr/share/desktop-directories/Network.directory
/usr/share/desktop-directories/Office.directory
/usr/share/desktop-directories/System-Tools.directory
/usr/share/desktop-directories/Utility-Accessibility.directory
/usr/share/desktop-directories/Utility.directory
/usr/share/desktop-directories/X-GNOME-Menu-Applications.directory
/usr/share/desktop-directories/X-GNOME-Other.directory
/usr/share/desktop-directories/X-GNOME-Sundry.directory
/usr/share/desktop-directories/X-GNOME-SystemSettings.directory
/usr/share/desktop-directories/X-GNOME-Utilities.directory
/usr/share/desktop-directories/X-GNOME-WebApplications.directory
/usr/share/gir-1.0/*.gir
/usr/share/xdg/menus/gnome-applications.menu

%files dev
%defattr(-,root,root,-)
/usr/include/gnome-menus-3.0/gmenu-tree.h
/usr/lib64/libgnome-menu-3.so
/usr/lib64/pkgconfig/libgnome-menu-3.0.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libgnome-menu-3.so.0
/usr/lib64/libgnome-menu-3.so.0.0.1

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/gnome-menus/COPYING
/usr/share/package-licenses/gnome-menus/COPYING.LIB

%files locales -f gnome-menus.lang
%defattr(-,root,root,-)

