#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : gnome-menus
Version  : 3.13.3
Release  : 4
URL      : http://ftp.gnome.org/pub/gnome/sources/gnome-menus/3.13/gnome-menus-3.13.3.tar.xz
Source0  : http://ftp.gnome.org/pub/gnome/sources/gnome-menus/3.13/gnome-menus-3.13.3.tar.xz
Summary  : Desktop Menu Specification Implementation
Group    : Development/Tools
License  : GPL-2.0 LGPL-2.0
Requires: gnome-menus-lib
Requires: gnome-menus-data
Requires: gnome-menus-locales
BuildRequires : gettext
BuildRequires : gobject-introspection-dev
BuildRequires : intltool
BuildRequires : perl(XML::Parser)
BuildRequires : pkgconfig(gio-unix-2.0)

%description
gnome-menus
===========
gnome-menus contains the libgnome-menu library, the layout configuration
files for the GNOME menu, as well as a simple menu editor.

%package data
Summary: data components for the gnome-menus package.
Group: Data

%description data
data components for the gnome-menus package.


%package dev
Summary: dev components for the gnome-menus package.
Group: Development
Requires: gnome-menus-lib
Requires: gnome-menus-data
Provides: gnome-menus-devel

%description dev
dev components for the gnome-menus package.


%package lib
Summary: lib components for the gnome-menus package.
Group: Libraries
Requires: gnome-menus-data

%description lib
lib components for the gnome-menus package.


%package locales
Summary: locales components for the gnome-menus package.
Group: Default

%description locales
locales components for the gnome-menus package.


%prep
%setup -q -n gnome-menus-3.13.3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1492791850
%configure --disable-static
make V=1  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1492791850
rm -rf %{buildroot}
%make_install
%find_lang gnome-menus-3.0
## make_install_append content
mv %{buildroot}/etc/xdg %{buildroot}/usr/share/. && rmdir %{buildroot}/etc
## make_install_append end

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/lib64/girepository-1.0/GMenu-3.0.typelib
/usr/share/desktop-directories/AudioVideo.directory
/usr/share/desktop-directories/Development.directory
/usr/share/desktop-directories/Education.directory
/usr/share/desktop-directories/Game.directory
/usr/share/desktop-directories/Graphics.directory
/usr/share/desktop-directories/Network.directory
/usr/share/desktop-directories/Office.directory
/usr/share/desktop-directories/System-Tools.directory
/usr/share/desktop-directories/Utility-Accessibility.directory
/usr/share/desktop-directories/Utility.directory
/usr/share/desktop-directories/X-GNOME-Menu-Applications.directory
/usr/share/desktop-directories/X-GNOME-Other.directory
/usr/share/desktop-directories/X-GNOME-Sundry.directory
/usr/share/desktop-directories/X-GNOME-SystemSettings.directory
/usr/share/desktop-directories/X-GNOME-Utilities.directory
/usr/share/desktop-directories/X-GNOME-WebApplications.directory
/usr/share/gir-1.0/*.gir
/usr/share/xdg/menus/gnome-applications.menu

%files dev
%defattr(-,root,root,-)
/usr/include/gnome-menus-3.0/gmenu-tree.h
/usr/lib64/libgnome-menu-3.so
/usr/lib64/pkgconfig/libgnome-menu-3.0.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libgnome-menu-3.so.0
/usr/lib64/libgnome-menu-3.so.0.0.1

%files locales -f gnome-menus-3.0.lang
%defattr(-,root,root,-)

